# Generated by Django 5.2.5 on 2025-08-12 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('korttisovellus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='description',
            new_name='kuvaus',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='title',
            new_name='otsikko',
        ),
    ]
