# Generated by Django 5.2.5 on 2025-08-13 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('korttisovellus', '0002_rename_description_card_kuvaus_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card',
            new_name='Kortti',
        ),
    ]
